# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d8189fe104795784990ac7cd398ba157c541749bd205744f32f56e359d69d1fc8057365f0ed72371649ed8460861a0f23e9f43973ec6ede100c21d3eeb07b51

test:
  secret_key_base: b14d61122e8ef5054fbe96d86145092d78228f7674f456c8715d3f522d8a1927df525fe1ddafcf1a74053af0e749828faa7fc938b847335a7fe2b1feebb50618

dev:
  secret_key_base: <%= begin IO.read(ENV['SECRET_KEY_BASE']).chomp rescue "" end %>

preprod:
  secret_key_base: <%= begin IO.read(ENV['SECRET_KEY_BASE']).chomp rescue "" end %>

production:
  secret_key_base: <%= begin IO.read(ENV['SECRET_KEY_BASE']).chomp rescue "" end %>
